image: docker:27.3.1
services:
  - name: docker:27.3.1-dind
    alias: docker

stages:
  - build
  - test
  - deploy

before_script:
  - docker version
  - docker compose version

build-job:
  stage: build
  tags: [build]
  script:
    - docker compose build

test-service2-job:
  stage: test
  tags: [test]
  script:
    - docker image ls
    - docker run --rm -p -d 8200:8200 devops-project-esa-service2 &
    - curl telnet://localhost:8200 | grep "Service2"

deploy-job:
  stage: deploy
  tags: [deploy]
  script:
    - docker compose up -d
