image: docker:27.3.1

services:
    - name: docker:27.3.1-dind
      alias: docker

build-job:
    stage: build
    tags: [build]
    script:
        - echo "Build"

test-job:
    stage: test
    tags: [test]
    script:
        - echo "Test"

deploy-job:
    stage: deploy
    tags: [deploy]
    script:
        - echo "Deploy"
