variables:
  DOCKER_HOST: tcp://docker:2375/

image: docker:27.3.1
services:
  - name: docker:27.3.1-dind
    alias: docker

scan-docker-port:
  image: alpine
  stage: build
  tags: [build]
  services:
    - docker:dind
  script:
    - apk add nmap
    - nmap -sT -p- docker

build-job:
  stage: build
  tags: [build]
  script:
    - docker compose build

test-job:
  stage: test
  tags: [test]
  script:
    - echo "Test"

deploy-job:
  stage: deploy
  tags: [deploy]
  script:
    - echo "Deploy"
