services:
  service1:
    build:
      context: src/Service1/
    environment:
      - PORT=8199
    depends_on:
      - service2
    deploy:
      replicas: 3
    networks:
      - backend
  service2:
    build:
      context: src/Service2/
    container_name: service2
    environment:
      - PORT=8200
    networks:
      - backend
  nginx:
    build: 
      context: src/nginx/
    container_name: nginx
    ports:
      - "8198:8198"
    networks:
      - backend
    depends_on:
      - service1
      - service2

networks:
  backend:
