services:
  service1:
    build:
      context: src/Service1/
    ports:
      - "8199:8199"
    depends_on:
      - service2 # This ensures that service2 is started first.
  service2:
    build:
      context: src/Service2/
    expose: # Here expose is used instead of ports, since the host machine does not need direct access to service2.
      - "8200"
