services:
  service1:
    build:
      context: src/Service1/
    environment:
      - PORT=8199
    depends_on:
      - service2
    deploy:
      replicas: 3
    networks:
      - backend
  service2:
    build:
      context: src/Service2/
    container_name: service2
    environment:
      - PORT=8200
    networks:
      - backend
  nginx:
    build: 
      context: src/nginx/
    container_name: nginx
    ports:
      - "8198:8198"
      - "8197:8197"
    networks:
      - backend
    depends_on:
      - service1
      - service2
      - controller
  controller:
    build:
      dockerfile: src/controller/Dockerfile
    # Here we expose the Docker socket to the container so that Docker commands can be run
    # on the host machine. Scary.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8197
    networks:
      - backend

networks:
  backend:
